### ISSUE TITLE
A probe block configured with a thickness less than 12.7mm will crash the spindle

### ISSUE THREAD

**Issue by wolfkabal** [OneFinityCNC/onefinity-firmware#1]
https://github.com/OneFinityCNC/onefinity-firmware/blob/0f67a1bcfa556c378c19930f0423146c43a968c9/src/js/control-view.js#L344

As it stands, the the `probe_xyz()` function will drop the z-axis -12.7mm in order to align for the X/Y probing. If a user configures a probe block height (in settings config) to a value less than 12.7mm, the unit will crash into the work piece or bed.

This value should be a percentage of the prob-zdim. 75%?

**Comment by dacarley** [comment]
Thanks for the report.  Is this something you experienced first-hand, or just a discovery from perusing the code?

**Comment by wolfkabal** [comment]
> Thanks for the report. Is this something you experienced first-hand, or just a discovery from perusing the code?

It was observed first hand by another user, and reported within the onefinity forums - https://forum.onefinitycnc.com/t/xyz-probe-routine-location/3822. But the code confirms and backs this up.

In the forum post, they tried using a probe-block with a thickness of 8.75mm, which resulted in the unit crashing into the workpiece.

**Comment by wolfkabal** [comment]
https://github.com/OneFinityCNC/onefinity-firmware/pull/7

**Comment by OneFinityCNC** [comment]
Thanks for the contribution.  Your work was incorporated into a general refactoring of the probing routines, and should be available in a release of the firmware soon!
