### ISSUE TITLE
BUG: FW 1.0.8: Horizontal lock, locks Z also and can’t lock horizontal and vertical at the same time.

### ISSUE THREAD

**Issue by satoer** [OneFinityCNC/onefinity-firmware#55]
I’ve discovered some bugs using the game pad:

- **Bug1:** If you press the top left button (horizontal lock), the Z axis gets also locked.
- **Bug2:** It’s not possible lock both X + Y axis by pushing the top left and the right button at the same time. (so you can only move the Z.

These might not seem a problem, but I’m developing a remote control panel with a 3 axis joystick based on a game controller, and these bugs are restraining it to get the full potential out of it.
![DSC04316-FB](https://user-images.githubusercontent.com/15175433/136230425-416edb64-ea97-48e8-9052-4830cfcb0ff6.jpg)

**Comment by dacarley** [comment]
The gamepad support code has been completely rewritten in v1.1.1.  It should support all common controllers, and custom support can be easily added for other gamepads.

This remote control panel looks pretty awesome.  Have you finished building it yet?
