### ISSUE TITLE
Docs on building and pushing to a machine?

### ISSUE THREAD

**Issue by Bigguy34** [OneFinityCNC/onefinity-firmware#64]
I have added a feature to be able to upload more than one file in the UI but I can't figure out how to push to my changes to my machine to test. The make file has a publish and an update. It appears that the update will push a firmware to a local machine possibly and the publish will push via rsync to a buildbotics server? Which is hopefully protected in some way? Can I use the update to push to my own machine by changing the HOST and PASSWORD? Are there docs for how to use the make file?

**Comment by dacarley** [comment]
See `docs/development.md` for complete instructions on how to build the controller firmware.

At the time of writing, the "v1.2.0-dev" branch has the most up-to-date instructions.
